<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jve_template"
 *
 * Auto generated by Extension Builder 2016-08-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['jv_contentblocks'] = array(
	'title' => 'JV_ Example Contentblocks',
	'description' => 'Collection of TYPO3 Contentblocks. Untested as standalone.',
	'category' => 'content',
	'author' => 'Jörg Velletti',
	'author_email' => 'typo3@velletti.de',
	'state' => 'beta',
	'internal' => '',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '12.4.4',
	'constraints' => array(
		'depends' => array(
			'typo3' => '12.4.0-12.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);